# Generated by Django 4.2.3 on 2024-07-19 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0002_remove_event_created_at_event_time_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='events',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='mycalendar.event'),
        ),
    ]
